name: gaussian_splatting_cuda12
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=22.3.1
  - pip:
    - torch==2.1.1 --index-url https://download.pytorch.org/whl/cu121
    - torchvision==0.16.1 --index-url https://download.pytorch.org/whl/cu121
    - torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu121
    - numpy<2
    - tqdm
    - plyfile
    - opencv-python
    - joblib

# - submodules/diff-gaussian-rasterization
# - submodules/simple-knn
# - submodules/fused-ssim